name: Greeting
# on: [push,workflow_dispatch]
on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
      - README.md
  workflow_dispatch:    
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            #   run: |
            #     echo "cloning repo.."
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Install node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            # - name: print node version
            #   run: node -v
            - name: cache depe
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
            - name: Installing Depe
              run: npm ci
            - name: Run tests
              run: npm run test       
    deploy:
        needs: greet
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: cache depe
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}    
            - name: Installing Depe
              run: npm ci
            - name: build 
              run: npm run build
            - name: Deploy
              run: echo "deploy successful"     
   

